#! /usr/bin/env bash
set -e

#Actual setup script
# Copy shared to ~/.local/share/nyxtra
source $HOME/.local/share/nyxtra/scripts/data/enviroment.sh



sudo cp -f $NYXTRA_HOME/defaults/pacman.conf /etc/pacman.conf
sudo pacman -Sy --noconfirm

bash $NYXTRA_HOME/scripts/install/install.sh
bash $NYXTRA_HOME/scripts/install/startup.sh
bash $NYXTRA_HOME/scripts/install/config.sh

sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
cp $NYXTRA_HOME/defaults/.zshrc $HOME/.zshrc