#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib/env.sh"


echo "User: $USER_NAME"
echo "Host: $HOST_NAME"
echo "Root: $NYXTRA_ROOT_DIR"

FIRST_VAR="${1:-}"
SECOND_VAR="${2:-}"
THIRD_VAR="${3:-}"

declare -A PHASE_DEFAULTS=(
    [pre]="system user pacman"
    [run]="system user"
    [post]="user"
)

#generate action file

#call actions from file in order
#if called with argument, only run that action/subaction

ACTIONS_FILE="$NYXTRA_ROOT_DIR/profiles/$HOST_NAME/$USER_NAME/actions.sh"

if [[ -f "$ACTIONS_FILE" ]]; then
    source "$ACTIONS_FILE"
else
    echo "Error: actions file not found: $ACTIONS_FILE" >&2
    exit 1
fi


source "$SCRIPT_DIR/lib/functions/run_layered.sh"

run_layered "$FIRST_VAR" "$SECOND_VAR" "$THIRD_VAR"