#!/bin/bash

# Array of npm packages to install globally for Neovim
npm_nvim=(
    typescript
    typescript-language-server
    prettier
    eslint
    eslint_d
    htmlhint
    vscode-langservers-extracted
    @vue/language-server
    @vue/typescript
    intelephense
)

post_install() {
    echo ">>> Installing Neovim npm packages..."
    # Use /usr/bin/env to ensure npm is found in PATH
    /usr/bin/env npm install -g "${npm_nvim[@]}"
}
