stream.rules = [
  {
    matches = [
      {
        application.process.binary = "zen-bin"
      }
    ]
    actions = {
      update-props = {
        target.object = "Virtual_Sink_Music"
      }
    }
  }
]